version: '3'
services:
  db:
    image: postgres:11
    container_name: db-rubyTest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    container_name: web-rubyTest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rubyTest
    ports:
      - "3000:3000"
    depends_on:
      - db